on:
  push:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.tool-versions'

      - uses: actions/cache@v3
        with:
          path: node_modules
          key: cache-${{ steps.setup-node.outputs.node-version }}-${{ hashFiles('package.json')}}

      - run: npm install

      # Added solely to surface the cache data
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { repo: { owner, repo } } = context;
            const { data } = await github.rest.actions.getActionsCacheList({ owner, repo })
            console.log(data)
            const summary = '```json\n' + JSON.stringify(data, null, 2) + '\n```'
            await core.summary.addRaw(JSON.stringify(data, null, 2)).write()
